# -*- coding: utf-8 -*-
"""IW Work 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEqtk54QSU5YkaAfwFBlQ1-ptaTJ0h8m

# Downloading the data from the sentiment analysis dataset and isolating the Spanish and English Reviews
"""

# @title
!pip install "datasets<2.20"

from huggingface_hub import login
from datasets import load_dataset
from google.colab import drive
drive.mount('/content/drive')
login()

import datasets
import pandas as pd
from datasets import load_dataset

dataset = load_dataset("Brand24/mms", split="train")

# Filter for english and spanish only
filtered = dataset.filter(lambda x: [lang in ["en", "es"] and dom == "reviews"
               for lang, dom in zip(x["language"], x["domain"])],
    batched=True)
filtered = filtered.select_columns(["text", "_id", "label", "language", "domain", "original_dataset"])

# Collect results into a list or dataframe
df = pd.DataFrame(filtered)

# Words between 10 - 20
df["word_count"] = df["text"].str.split().str.len()
df = df[(df["word_count"] >= 10) & (df["word_count"] <= 20)]

# saving full dataset to drive
df.to_parquet("/content/drive/MyDrive/mms_filtered.parquet", index=False)

# Then split by language
df_es = df[df["language"] == "es"]
df_en = df[df["language"] == "en"]

print(f"Spanish: {len(df_es)} rows")
print(f"English: {len(df_en)} rows")

"""Focus only on sentences with 10 - 20 words"""

# @title
df_en_sample = df_en.groupby("label").sample(n=3000, random_state=42)
df_es_sample = df_es.groupby("label").sample(n=3000, random_state=42)

# saving each to drive
df_en_sample.to_parquet("/content/drive/MyDrive/mms_en_sample.parquet", index=False)
df_es_sample.to_parquet("/content/drive/MyDrive/mms_es_sample.parquet", index=False)

print(f"English sample: {len(df_en_sample)} rows")
print(df_en_sample["label"].value_counts())

print(f"\nSpanish sample: {len(df_es_sample)} rows")
print(df_es_sample["label"].value_counts())

"""# ***Download Each dataset from drive***"""

from google.colab import drive
import pandas as pd
!pip install colab-mcp

drive.mount('/content/drive')

df = pd.read_parquet("/content/drive/MyDrive/mms_filtered.parquet")
df_en_sample = pd.read_parquet("/content/drive/MyDrive/mms_en_sample.parquet")
df_es_sample = pd.read_parquet("/content/drive/MyDrive/mms_es_sample.parquet")

print(f"Full filtered: {len(df)} rows")
print(f"English sample: {len(df_en_sample)} rows")
print(f"Spanish sample: {len(df_es_sample)} rows")

"""# Build Vocabularies for each dataset"""

# @title
!wget https://dl.fbaipublicfiles.com/arrival/dictionaries/en-es.txt -O en-es.txt
!wget https://dl.fbaipublicfiles.com/arrival/dictionaries/es-en.txt -O es-en.txt
!pip install scikit-learn
!pip install spacy
!pip install triton --upgrade
!pip install transformers --upgrade
!python -m spacy download en_core_web_md
!python -m spacy download es_core_news_md
!pip install wordfreq

import os
import torch
import spacy
import pickle
import random
import numpy as np
import pandas as pd
from tqdm import tqdm
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
from transformers import (
    MarianMTModel,
    MarianTokenizer,
    AutoTokenizer,
    AutoModelForMaskedLM,
    pipeline
)
from wordfreq import top_n_list, word_frequency

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

nlp_en = spacy.load("en_core_web_md")
nlp_es = spacy.load("es_core_news_md")

def load_muse_dictionary(path):
    pairs = {}
    with open(path, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) != 2:
                continue
            src, tgt = parts
            src, tgt = src.lower(), tgt.lower()
            if src != tgt and src.isalpha() and tgt.isalpha():
                if src not in pairs:
                    pairs[src] = []
                pairs[src].append(tgt)
    print(f"Loaded {len(pairs)} source words from {path}")
    return pairs

print("Loading MUSE dictionaries...")
en_to_es_dict = load_muse_dictionary("en-es.txt")
es_to_en_dict = load_muse_dictionary("es-en.txt")

"""Building Vocabulary Using SpaCy medium models"""

# @title
model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2", device=device)

# Load translation models
print("Loading translation models...")
en_es_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-es")
en_es_model = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-es").to(device)

es_en_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-es-en")
es_en_model = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-es-en").to(device)

print("Loading MLM model...")
mlm_tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
mlm_model = AutoModelForMaskedLM.from_pretrained("bert-base-multilingual-cased").to(device)


from functools import lru_cache

@lru_cache(maxsize=10000)
def translate_sentence(sentence, source_lang="en"):
    if source_lang == "en":
        tokenizer, trans_model = en_es_tokenizer, en_es_model
    else:
        tokenizer, trans_model = es_en_tokenizer, es_en_model

    inputs = tokenizer([sentence], return_tensors="pt",
                       padding=True, truncation=True, max_length=512).to(device)
    with torch.no_grad():
        translated = trans_model.generate(**inputs)
    return tokenizer.decode(translated[0], skip_special_tokens=True)


def get_best_replacement(sentence, token, target_lemma, source_lang="en"):
    target_lang = "es" if source_lang == "en" else "en"
    target_nlp = nlp_es if target_lang == "es" else nlp_en

    if token.pos_ == "VERB":
        translated_sentence = translate_sentence(sentence, source_lang)
        target_doc = target_nlp(translated_sentence)

        for t in target_doc:
            if t.pos_ == "VERB" and t.lemma_.lower() == target_lemma:
                return t.text.lower()
        return target_lemma
    else:
        return target_lemma


def score_in_context(sentence, original_word, replacement):
    masked = sentence.replace(original_word, mlm_tokenizer.mask_token, 1)
    inputs = mlm_tokenizer(masked, return_tensors="pt",
                           truncation=True, max_length=512).to(device)

    mask_idx = (inputs["input_ids"] == mlm_tokenizer.mask_token_id).nonzero(as_tuple=True)[1]
    if len(mask_idx) == 0:
        return float("-inf")

    with torch.no_grad():
        outputs = mlm_model(**inputs)

    logits = outputs.logits[0, mask_idx[0]]
    probs = torch.log_softmax(logits, dim=-1)

    token_id = mlm_tokenizer.convert_tokens_to_ids(replacement)
    if token_id == mlm_tokenizer.unk_token_id:
        return float("-inf")

    return probs[token_id].item()


def verify_semantic_similarity(source_word, replacement, threshold=0.5):
    embeddings = model.encode([source_word, replacement], convert_to_numpy=True)
    similarity = float(cosine_similarity([embeddings[0]], [embeddings[1]])[0][0])
    return similarity >= threshold, similarity


def get_position(token, doc):
    for sent in doc.sents:
        if token.i >= sent.start and token.i < sent.end:
            sent_length = sent.end - sent.start
            relative_pos = token.i - sent.start
            third = sent_length / 3
            if relative_pos < third:
                return "beginning"
            elif relative_pos < third * 2:
                return "middle"
            else:
                return "end"
    return "middle"


def swap_word(sentence, source_lang="en", pos=None, position=None):
    dictionary = en_to_es_dict if source_lang == "en" else es_to_en_dict
    nlp = nlp_en if source_lang == "en" else nlp_es
    target_lang = "es" if source_lang == "en" else "en"

    doc = nlp(sentence)

    if pos:
        eligible = [token for token in doc if token.pos_ == pos.upper()]
    else:
        eligible = [token for token in doc if token.pos_ in ["NOUN", "ADJ", "VERB"]]

    if position:
        eligible = [token for token in eligible
                    if get_position(token, doc) == position.lower()]

    if not eligible:
        return "no_eligible"

    token = eligible[0]
    lookup = token.lemma_.lower() if token.pos_ == "VERB" else token.text.lower()

    if lookup not in dictionary:
        return "no_candidates"

    translations = dictionary[lookup]

    for target_lemma in translations:
        if target_lemma == lookup:
            continue

        target_freq = word_frequency(target_lemma, target_lang)
        source_freq = word_frequency(target_lemma, source_lang)
        if target_freq < source_freq:
            continue

        replacement = get_best_replacement(sentence, token, target_lemma, source_lang)

        context_score = score_in_context(sentence, token.text, replacement)
        if context_score == float("-inf"):
            context_score = score_in_context(sentence, token.text, target_lemma)
            if context_score == float("-inf"):
                continue
            replacement = target_lemma

        is_similar, similarity = verify_semantic_similarity(token.text, replacement)
        if not is_similar:
            continue

        swapped = sentence.replace(token.text, replacement, 1)
        return {
            "sentence": swapped,
            "original_word": token.text,
            "replacement": replacement,
            "similarity": similarity,
            "context_score": context_score
        }

    return "no_candidates"

"""# Building the architecture for word swapping

Swap Using word mappings
"""

# @title
# Test it
print(swap_word("I make food", source_lang="en", pos="VERB"))
print(swap_word("Excellent saw. I bought for cutting up fallen trees and exercise. Tones the brazos nicely.", source_lang="en", pos="VERB", position="middle"))
print(swap_word("El café estaba absolutamente terrible", source_lang="es", pos="NOUN"))

"""Testing the Swapping function"""

# @title
def test_swap_words(df, source_lang="en", n=10, seed=42):
    """Test swap_word on a random sample of sentences."""
    sample = df.sample(n=n, random_state=seed)

    for idx, row in sample.iterrows():
        sentence = row["text"]
        print(f"\n{'='*60}")
        print(f"Original: {sentence}")
        print(f"Label: {row['label']}")
        print("-" * 60)

        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                result = swap_word(sentence, source_lang=source_lang,
                                   pos=pos, position=position)

                if result == "no_eligible":
                    print(f"{pos:<6} {position:<12} → no eligible token")
                elif result == "no_candidates":
                    print(f"{pos:<6} {position:<12} → no candidates found")
                else:
                    print(f"{pos:<6} {position:<12} → '{result['original_word']}' "
                          f"replaced with '{result['replacement']}' "
                          f"(similarity: {result['similarity']:.3f})")
                    print(f"{'':20} {result['sentence']}")

# Test on English
test_swap_words(df_en_sample, source_lang="en", n=10)

# Test on Spanish
test_swap_words(df_es_sample, source_lang="es", n=10)

"""Analyzing Sentences"""

# @title
!pip install transformers
from transformers import pipeline

# Load multilingual sentiment model
sentiment_model = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment",
    device=0 if torch.cuda.is_available() else -1
)

def get_sentiment_score(text):
    """Returns sentiment as a score from 1-5."""
    try:
        result = sentiment_model(text[:512])[0]  # truncate to model max length
        # Model returns '1 star' to '5 stars' as labels
        score = int(result["label"].split()[0])
        return score, result["score"]  # score 1-5, confidence
    except:
        return None, None


def analyze_dataset(df, source_lang="en"):
    all_results = []

    # First pass - collect all sentences and swaps
    print("Generating swaps...")
    rows_data = []
    for idx, row in tqdm(df.iterrows(), total=len(df)):
        sentence = row["text"]
        row_data = {"original_text": sentence, "label": row["label"]}
        row_data["no_eligible_count"] = 0
        row_data["no_candidates_count"] = 0

        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                swap_result = swap_word(sentence, source_lang=source_lang,
                                       pos=pos, position=position)
                key = f"{pos}_{position}"
                if swap_result == "no_eligible":
                    row_data["no_eligible_count"] += 1
                    row_data[f"{key}_sentence"] = None
                elif swap_result == "no_candidates":
                    row_data["no_candidates_count"] += 1
                    row_data[f"{key}_sentence"] = None
                else:
                    row_data[f"{key}_sentence"] = swap_result["sentence"]
                    row_data[f"{key}_original_word"] = swap_result["original_word"]
                    row_data[f"{key}_replacement"] = swap_result["replacement"]
                    row_data[f"{key}_similarity"] = swap_result["similarity"]

        rows_data.append(row_data)

    # Collect all sentences that need sentiment analysis
    print("Collecting sentences for sentiment analysis...")
    all_sentences = []
    for row_data in rows_data:
        all_sentences.append(row_data["original_text"])
        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                key = f"{pos}_{position}"
                if row_data.get(f"{key}_sentence") is not None:
                    all_sentences.append(row_data[f"{key}_sentence"])

    # Second pass - batch sentiment analysis
    print(f"Running sentiment analysis on {len(all_sentences)} sentences...")
    sentiment_results = sentiment_model(
        all_sentences,
        batch_size=64,
        truncation=True,
        max_length=512
    )

    # Map sentences to their sentiment scores
    sentiment_map = {}
    for sentence, result in zip(all_sentences, sentiment_results):
        score = int(result["label"].split()[0])
        sentiment_map[sentence] = (score, result["score"])

    # Third pass - assemble final results
    print("Assembling results...")
    for row_data in rows_data:
        orig_score, orig_conf = sentiment_map[row_data["original_text"]]
        row_data["original_score"] = orig_score
        row_data["original_confidence"] = orig_conf

        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                key = f"{pos}_{position}"
                swapped_sentence = row_data.get(f"{key}_sentence")
                if swapped_sentence is not None:
                    swap_score, swap_conf = sentiment_map[swapped_sentence]
                    row_data[f"{key}_score"] = swap_score
                    row_data[f"{key}_confidence"] = swap_conf
                    row_data[f"{key}_score_diff"] = swap_score - orig_score

        all_results.append(row_data)

    return pd.DataFrame(all_results)


# Run on both datasets
print("Analyzing English dataset...")
df_en_results = analyze_dataset(df_en_sample, source_lang="en")

print("\nAnalyzing Spanish dataset...")
df_es_results = analyze_dataset(df_es_sample, source_lang="es")

# Save results
df_en_results.to_parquet("/content/drive/MyDrive/en_sentiment_results.parquet", index=False)
df_es_results.to_parquet("/content/drive/MyDrive/es_sentiment_results.parquet", index=False)

print(df_en_results.head())
print(df_es_results.head())

"""Print Swap Analysis"""

# @title
# Reload in future sessions without rerunning analysis
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

df_en_results = pd.read_parquet("/content/drive/MyDrive/en_sentiment_results.parquet")
df_es_results = pd.read_parquet("/content/drive/MyDrive/es_sentiment_results.parquet")

print(f"English results: {len(df_en_results)} rows")
print(f"Spanish results: {len(df_es_results)} rows")


def print_swap_analysis(df_results, lang="en"):
    positions = ["beginning", "middle", "end"]
    pos_tags = ["NOUN", "ADJ", "VERB"]

    print(f"\n{'='*60}")
    print(f"Swap Analysis - {lang.upper()}")
    print(f"{'='*60}\n")

    print(f"{'':15}", end="")
    for position in positions:
        print(f"{position:>20}", end="")
    print()
    print("-" * 75)

    for pos in pos_tags:
        print(f"{pos:<15}", end="")
        for position in positions:
            key = f"{pos}_{position}"
            sentence_col = f"{key}_sentence"
            diff_col = f"{key}_score_diff"

            if sentence_col not in df_results.columns:
                print(f"{'N/A':>20}", end="")
                continue

            successful_swaps = df_results[sentence_col].notna()
            total_successful = successful_swaps.sum()

            if total_successful == 0:
                print(f"{'0/0':>20}", end="")
                continue

            sentiment_shifted = (
                df_results.loc[successful_swaps, diff_col].notna() &
                (df_results.loc[successful_swaps, diff_col] != 0)
            ).sum()

            # Format fraction as a single string first, then pad
            fraction = f"{sentiment_shifted}/{total_successful}"
            print(f"{fraction:>20}", end="")
        print()

    print("-" * 75)
    total_no_eligible = df_results["no_eligible_count"].sum()
    total_no_candidates = df_results["no_candidates_count"].sum()
    print(f"\nTotal skipped - no eligible token: {total_no_eligible}")
    print(f"Total skipped - no candidates:     {total_no_candidates}")
    print()

print_swap_analysis(df_en_results, lang="English")
print_swap_analysis(df_es_results, lang="Spanish")

"""Analyze specific cases where there was a sentiment shift"""

# @title
# Add direction parameter
def show_sentiment_shifts(df_results, n=10, min_diff=1,
                          pos_filter=None, direction=None):
    """
    Show examples of sentences where a sentiment shift occurred.
    min_diff: minimum absolute score difference to show
    """
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]

    examples = []

    for idx, row in df_results.iterrows():
        for pos in pos_tags:
            for position in positions:
                key = f"{pos}_{position}"
                diff_col = f"{key}_score_diff"
                sentence_col = f"{key}_sentence"

                if diff_col not in df_results.columns:
                    continue
                if pd.isna(row[diff_col]) or pd.isna(row[sentence_col]):
                    continue
                if abs(row[diff_col]) >= min_diff:
                  if direction == "negative" and row[diff_col] >= 0:
                      continue
                  if direction == "positive" and row[diff_col] <= 0:
                      continue
                  if pos_filter and pos != pos_filter:
                      continue
                  examples.append({
                        "original": row["original_text"],
                        "swapped": row[sentence_col],
                        "original_word": row[f"{key}_original_word"],
                        "replacement": row[f"{key}_replacement"],
                        "original_score": row["original_score"],
                        "swapped_score": row[f"{key}_score"],
                        "score_diff": row[diff_col],
                        "pos": pos,
                        "position": position
                  })

    # Sort by absolute score diff
    examples = sorted(examples, key=lambda x: abs(x["score_diff"]), reverse=True)

    # Print top n
    for ex in examples[:n]:
        print(f"\n{'='*60}")
        print(f"POS: {ex['pos']} | Position: {ex['position']} | "
              f"Diff: {int(ex['score_diff']):+d}")
        print(f"Original  ({int(ex['original_score'])} stars): {ex['original']}")
        print(f"Swapped   ({int(ex['swapped_score'])} stars): {ex['swapped']}")
        print(f"Swap: '{ex['original_word']}' → '{ex['replacement']}'")

# Show top 10 largest shifts
print("=== NEGATIVE ENGLISH SENTIMENT SHIFTS ===")
# Only show cases where sentiment got worse
show_sentiment_shifts(df_en_results, n=10, min_diff=1, direction="negative")

print("\n=== POSITIVE ENGLISH SENTIMENT SHIFTS ===")
# Only show cases where sentiment got worse
show_sentiment_shifts(df_en_results, n=10, min_diff=1, direction="positive")

print("\n=== NEGATIVE SPANISH SENTIMENT SHIFTS ===")
show_sentiment_shifts(df_es_results, n=10, min_diff=1, direction="negative")

print("\n=== POSITIVE SPANISH SENTIMENT SHIFTS ===")
show_sentiment_shifts(df_es_results, n=10, min_diff=1, direction="positive")

"""Analysis Across 6 Metrics"""

# @title
from sentence_transformers import SentenceTransformer, util
import numpy as np
import pandas as pd
from tqdm import tqdm

# Load LaBSE for semantic similarity (better for multilingual)
labse_model = SentenceTransformer("sentence-transformers/LaBSE", device=device)

# ================================================================
# METRIC 1: Flip Rate (FR)
# ================================================================
def compute_flip_rate(df_results, lang=""):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    flip_rates = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"Flip Rate {lang}"):
        key = f"{pos}_{position}"
        diff_col = f"{key}_score_diff"
        sentence_col = f"{key}_sentence"

        if sentence_col not in df_results.columns:
            continue

        swapped = df_results[sentence_col].notna()
        total = swapped.sum()
        if total == 0:
            continue

        flipped = (df_results.loc[swapped, diff_col] != 0).sum()
        flip_rates[key] = {
            "flipped": int(flipped),
            "total": int(total),
            "rate": float(flipped / total)
        }

    return flip_rates


# ================================================================
# METRIC 2: Minimum Swap Distance to Flip (MSDF)
# ================================================================
# def compute_msdf(df, source_lang="en", max_swaps=9):
#     ...


# ================================================================
# METRIC 3: Semantic Similarity (SemSim)
# ================================================================
def compute_semsim(df_results, lang=""):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    semsim_results = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"SemSim {lang}"):
        key = f"{pos}_{position}"
        sentence_col = f"{key}_sentence"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()]
        if len(valid) == 0:
            continue

        orig_sentences = valid["original_text"].tolist()
        swap_sentences = valid[sentence_col].tolist()

        orig_embeddings = labse_model.encode(orig_sentences,
                                              batch_size=64,
                                              convert_to_numpy=True,
                                              show_progress_bar=False)
        swap_embeddings = labse_model.encode(swap_sentences,
                                              batch_size=64,
                                              convert_to_numpy=True,
                                              show_progress_bar=False)

        sims = [float(util.cos_sim(o, s))
                for o, s in zip(orig_embeddings, swap_embeddings)]

        diff_col = f"{key}_score_diff"
        high_sim_mask = np.array(sims) >= 0.8
        flipped = (valid[diff_col].values != 0)

        flip_at_high_sim = (high_sim_mask & flipped).sum()
        total_high_sim = high_sim_mask.sum()

        semsim_results[key] = {
            "mean_similarity": float(np.mean(sims)),
            "flip_rate_at_high_sim": float(flip_at_high_sim / total_high_sim)
                                      if total_high_sim > 0 else 0.0,
            "total_high_sim": int(total_high_sim)
        }

    return semsim_results


# ================================================================
# METRIC 4: Robustness Gap
# ================================================================
def compute_robustness_gap(df_results, lang=""):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    label_map = {0: 1, 1: 3, 2: 5}

    def is_correct(pred_score, true_label):
        true_score = label_map.get(true_label)
        if true_score is None:
            return False
        def to_class(s):
            if s <= 2: return "negative"
            elif s == 3: return "neutral"
            else: return "positive"
        return to_class(pred_score) == to_class(true_score)

    orig_correct = df_results.apply(
        lambda r: is_correct(r["original_score"], r["label"]), axis=1
    ).mean()

    gaps = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"Robustness Gap {lang}"):
        key = f"{pos}_{position}"
        score_col = f"{key}_score"
        sentence_col = f"{key}_sentence"

        if score_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()].copy()
        if len(valid) == 0:
            continue

        swap_correct = valid.apply(
            lambda r: is_correct(r[score_col], r["label"]), axis=1
        ).mean()

        gaps[key] = {
            "original_accuracy": float(orig_correct),
            "swapped_accuracy": float(swap_correct),
            "robustness_gap": float(orig_correct - swap_correct)
        }

    return gaps


# ================================================================
# METRIC 5: Flip Rate by Language Mixing Index (LMI)
# ================================================================
def compute_lmi(sentence, lang="en"):
    words = sentence.lower().split()
    if not words:
        return 0.0

    other_lang = "es" if lang == "en" else "en"
    other_count = sum(
        1 for w in words
        if word_frequency(w, other_lang) > word_frequency(w, lang)
    )
    return other_count / len(words)

def compute_flip_rate_by_lmi(df_results, source_lang="en", n_bins=5):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    lmi_flip_data = []
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"LMI {source_lang.upper()}"):
        key = f"{pos}_{position}"
        sentence_col = f"{key}_sentence"
        diff_col = f"{key}_score_diff"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()].copy()
        if len(valid) == 0:
            continue

        valid["lmi"] = valid[sentence_col].apply(
            lambda s: compute_lmi(s, lang=source_lang)
        )
        valid["flipped"] = valid[diff_col] != 0
        valid["swap_key"] = key
        lmi_flip_data.append(valid[["lmi", "flipped", "swap_key"]])

    if not lmi_flip_data:
        return None

    combined = pd.concat(lmi_flip_data)
    combined["lmi_bin"] = pd.cut(combined["lmi"], bins=n_bins)
    lmi_summary = combined.groupby("lmi_bin")["flipped"].agg(["mean", "count"])
    lmi_summary.columns = ["flip_rate", "count"]
    return lmi_summary


# ================================================================
# METRIC 6: Per-Language-Pair Asymmetry
# ================================================================
def compute_asymmetry(df_en_results, df_es_results):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    asymmetry = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc="Asymmetry EN↔ES"):
        key = f"{pos}_{position}"
        diff_col = f"{key}_score_diff"
        sentence_col = f"{key}_sentence"

        if sentence_col in df_en_results.columns:
            en_valid = df_en_results[df_en_results[sentence_col].notna()]
            en_flips = (en_valid[diff_col] != 0).sum()
            en_total = len(en_valid)
            en_rate = en_flips / en_total if en_total > 0 else 0
        else:
            en_rate, en_total = 0, 0

        if sentence_col in df_es_results.columns:
            es_valid = df_es_results[df_es_results[sentence_col].notna()]
            es_flips = (es_valid[diff_col] != 0).sum()
            es_total = len(es_valid)
            es_rate = es_flips / es_total if es_total > 0 else 0
        else:
            es_rate, es_total = 0, 0

        asymmetry[key] = {
            "en_to_es_flip_rate": float(en_rate),
            "es_to_en_flip_rate": float(es_rate),
            "asymmetry": float(en_rate - es_rate)
        }

    return asymmetry


# ================================================================
# RUN ALL METRICS
# ================================================================
print("Computing Flip Rates...")
fr_en = compute_flip_rate(df_en_results, lang="EN")
fr_es = compute_flip_rate(df_es_results, lang="ES")

print("\nComputing Semantic Similarity...")
semsim_en = compute_semsim(df_en_results, lang="EN")
semsim_es = compute_semsim(df_es_results, lang="ES")

print("\nComputing Robustness Gap...")
gap_en = compute_robustness_gap(df_en_results, lang="EN")
gap_es = compute_robustness_gap(df_es_results, lang="ES")

print("\nComputing LMI Flip Rates...")
lmi_en = compute_flip_rate_by_lmi(df_en_results, source_lang="en")
lmi_es = compute_flip_rate_by_lmi(df_es_results, source_lang="es")

print("\nComputing Asymmetry...")
asymmetry = compute_asymmetry(df_en_results, df_es_results)

print("\nDone!")

# print("\nComputing MSDF (this may take a while)...")
# msdf_en = compute_msdf(df_en_sample, source_lang="en")
# msdf_es = compute_msdf(df_es_sample, source_lang="es")



"""Print Results Summary"""

# @title
!pip install transformers
from transformers import pipeline

def print_all_metrics(fr, semsim, gap, lmi, asymmetry, lang="en"):
    print(f"\n{'='*60}")
    print(f"FULL METRICS REPORT - {lang.upper()}")
    print(f"{'='*60}")

    print(f"\n--- Flip Rate ---")
    for key, val in fr.items():
        print(f"{key:<20} {val['flipped']}/{val['total']} "
              f"({val['rate']*100:.1f}%)")

    print(f"\n--- Semantic Similarity & Flip Rate at High SemSim ---")
    for key, val in semsim.items():
        print(f"{key:<20} mean_sim={val['mean_similarity']:.3f} "
              f"flip@sim>=0.8={val['flip_rate_at_high_sim']*100:.1f}% "
              f"(n={val['total_high_sim']})")

    print(f"\n--- Robustness Gap ---")
    for key, val in gap.items():
        print(f"{key:<20} orig_acc={val['original_accuracy']*100:.1f}% "
              f"swap_acc={val['swapped_accuracy']*100:.1f}% "
              f"gap={val['robustness_gap']*100:.1f}%")

    print(f"\n--- LMI Flip Rate ---")
    print(lmi)

    print(f"\n--- Asymmetry (en->es vs es->en) ---")
    for key, val in asymmetry.items():
        print(f"{key:<20} en->es={val['en_to_es_flip_rate']*100:.1f}% "
              f"es->en={val['es_to_en_flip_rate']*100:.1f}% "
              f"diff={val['asymmetry']*100:+.1f}%")

    # print(f"\n--- MSDF ---")
    # print(f"Mean min swaps to flip: {msdf['min_swaps_to_flip'].mean():.2f}")
    # print(f"Never flipped: {msdf['min_swaps_to_flip'].isna().sum()} sentences")
    # print(msdf['min_swaps_to_flip'].value_counts().sort_index())

print_all_metrics(fr_en, semsim_en, gap_en, lmi_en, asymmetry, lang="en")
print_all_metrics(fr_es, semsim_es, gap_es, lmi_es, asymmetry, lang="es")

"""# **Analysis and Cross Comparison for each model **"""

# @title
!pip install transformers
!pip install "datasets<2.20" wordfreq sentence-transformers transformers spacy
!python -m spacy download en_core_web_md
!python -m spacy download es_core_news_md
import os
import gc
import pickle
import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
from wordfreq import word_frequency
from google.colab import drive

# HuggingFace / transformers
from transformers import (
    MarianMTModel,
    MarianTokenizer,
    pipeline
)

# Sentence embeddings (used in compute_semsim)
from sentence_transformers import SentenceTransformer, util

# spaCy models (must also be downloaded)
import spacy
nlp_en = spacy.load("en_core_web_md")
nlp_es = spacy.load("es_core_news_md")

device = "cuda" if torch.cuda.is_available() else "cpu"

drive.mount('/content/drive')

df_en_sample = pd.read_parquet("/content/drive/MyDrive/mms_en_sample.parquet")
df_es_sample = pd.read_parquet("/content/drive/MyDrive/mms_es_sample.parquet")

# Load translation models
print("Loading translation models...")
en_es_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-es")
en_es_model = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-es").to(device)

es_en_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-es-en")
es_en_model = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-es-en").to(device)

# @title
from functools import lru_cache
import pandas as pd
from tqdm.notebook import tqdm
from wordfreq import word_frequency
from google.colab import drive
from transformers import pipeline
import torch
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

drive.mount('/content/drive')

# df_en_results and df_es_results are loaded here, but we will re-generate them
# with the new approach for each model, so these initial loads might be redundant
# depending on the full script execution order. Keeping them for now for context
# if other parts of the notebook rely on them.
df_en_results_initial = pd.read_parquet("/content/drive/MyDrive/en_sentiment_results.parquet")
df_es_results_initial = pd.read_parquet("/content/drive/MyDrive/es_sentiment_results.parquet")

print(f"English results (initial load): {len(df_en_results_initial)} rows")
print(f"Spanish results (initial load): {len(df_es_results_initial)} rows")

models_to_test = {
    "mbert": "nlptown/bert-base-multilingual-uncased-sentiment",
    "xlm_roberta": "cardiffnlp/twitter-xlm-roberta-base-sentiment",
    "distilbert": "lxyuan/distilbert-base-multilingual-cased-sentiments-student"
}

def get_sentiment_score_generic(text, model_pipeline, model_key):
    """Handle different model output formats."""
    try:
        result = model_pipeline(text[:512])[0]  # truncate to model max length
        label = result["label"]
        score = result["score"]

        if model_key == "mbert":
            # Returns '1 star' to '5 stars'
            numeric = int(label.split()[0])
        elif model_key == "xlm_roberta":
            # Returns 'negative', 'neutral', 'positive'
            label_map = {"negative": 1, "neutral": 3, "positive": 5}
            numeric = label_map.get(label.lower(), 3)
        elif model_key == "distilbert":
            # Returns 'negative', 'positive'
            label_map = {"negative": 1, "positive": 5}
            numeric = label_map.get(label.lower(), 3)

        return numeric, score
    except:
        return None, None

@lru_cache(maxsize=10000)
def translate_sentence(sentence, source_lang="en"):
    if source_lang == "en":
        tokenizer, trans_model = en_es_tokenizer, en_es_model
    else:
        tokenizer, trans_model = es_en_tokenizer, es_en_model

    inputs = tokenizer([sentence], return_tensors="pt",
                       padding=True, truncation=True, max_length=512).to(device)
    with torch.no_grad():
        translated = trans_model.generate(**inputs)
    return tokenizer.decode(translated[0], skip_special_tokens=True)

def get_best_replacement(sentence, token, target_lemma, source_lang="en"):
    target_lang = "es" if source_lang == "en" else "en"
    target_nlp = nlp_es if target_lang == "es" else nlp_en

    if token.pos_ == "VERB":
        translated_sentence = translate_sentence(sentence, source_lang)
        target_doc = target_nlp(translated_sentence)

        for t in target_doc:
            if t.pos_ == "VERB" and t.lemma_.lower() == target_lemma:
                return t.text.lower()
        return target_lemma
    else:
        return target_lemma

def score_in_context(sentence, original_word, replacement):
    masked = sentence.replace(original_word, mlm_tokenizer.mask_token, 1)
    inputs = mlm_tokenizer(masked, return_tensors="pt",
                           truncation=True, max_length=512).to(device)

    mask_idx = (inputs["input_ids"] == mlm_tokenizer.mask_token_id).nonzero(as_tuple=True)[1]
    if len(mask_idx) == 0:
        return float("-inf")

    with torch.no_grad():
        outputs = mlm_model(**inputs)

    logits = outputs.logits[0, mask_idx[0]]
    probs = torch.log_softmax(logits, dim=-1)

    token_id = mlm_tokenizer.convert_tokens_to_ids(replacement)
    if token_id == mlm_tokenizer.unk_token_id:
        return float("-inf")

    return probs[token_id].item()

def verify_semantic_similarity(source_word, replacement, threshold=0.5):
    embeddings = model.encode([source_word, replacement], convert_to_numpy=True)
    similarity = float(cosine_similarity([embeddings[0]], [embeddings[1]])[0][0])
    return similarity >= threshold, similarity

def get_position(token, doc):
    for sent in doc.sents:
        if token.i >= sent.start and token.i < sent.end:
            sent_length = sent.end - sent.start
            relative_pos = token.i - sent.start
            third = sent_length / 3
            if relative_pos < third:
                return "beginning"
            elif relative_pos < third * 2:
                return "middle"
            else:
                return "end"
    return "middle"

def swap_word_fast(sentence, doc, translated_doc, source_lang="en", pos=None, position=None, exclude_words=None):
    dictionary = en_to_es_dict if source_lang == "en" else es_to_en_dict

    if exclude_words is None:
        exclude_words = set()

    if pos:
        eligible = [token for token in doc if token.pos_ == pos.upper() and token.text.lower() not in exclude_words]
    else:
        eligible = [token for token in doc if token.pos_ in ["NOUN", "ADJ", "VERB"] and token.text.lower() not in exclude_words]

    if position:
        eligible = [token for token in eligible
                    if get_position(token, doc) == position.lower()]

    if not eligible:
        return "no_eligible"

    token = eligible[0]
    lookup = token.lemma_.lower() if token.pos_ == "VERB" else token.text.lower()

    if lookup not in dictionary:
        return "no_candidates"

    translations = dictionary[lookup]

    for target_lemma in translations:
        if target_lemma == lookup:
            continue

        target_lang = "es" if source_lang == "en" else "en"
        target_freq = word_frequency(target_lemma, target_lang)
        source_freq = word_frequency(target_lemma, source_lang)
        if target_freq < source_freq:
            continue

        replacement = get_best_replacement(sentence, token, target_lemma, source_lang)

        context_score = score_in_context(sentence, token.text, replacement)
        if context_score == float("-inf"):
            context_score = score_in_context(sentence, token.text, target_lemma)
            if context_score == float("-inf"):
                continue
            replacement = target_lemma

        is_similar, similarity = verify_semantic_similarity(token.text, replacement)
        if not is_similar:
            continue

        swapped = sentence.replace(token.text, replacement, 1)
        return {
            "sentence": swapped,
            "original_word": token.text,
            "replacement": replacement,
            "similarity": similarity,
            "context_score": context_score
        }

    return "no_candidates"

def _preprocess_and_generate_swaps(df, source_lang="en"):
    """
    Generates all possible swaps and their metadata (excluding sentiment scores).
    This function performs pre-translation, pre-parsing, and swap generation once.
    """
    print(f"Pre-processing and generating swaps for {source_lang.upper()} dataset...")
    all_rows_data = []

    if source_lang == "en":
        tokenizer, trans_model = en_es_tokenizer, en_es_model
        source_nlp = nlp_en
        target_nlp = nlp_es
    else:
        tokenizer, trans_model = es_en_tokenizer, es_en_model
        source_nlp = nlp_es
        target_nlp = nlp_en

    texts = df["text"].tolist()
    translations = {}

    print("  Pre-translating sentences...")
    for i in tqdm(range(0, len(texts), 64), desc="  Translating"):
        batch = texts[i:i+64]
        inputs = tokenizer(batch, return_tensors="pt", padding=True,
                          truncation=True, max_length=512).to(device)
        with torch.no_grad():
            translated = trans_model.generate(**inputs)
        for src, tgt in zip(batch, translated):
            translations[src] = tokenizer.decode(tgt, skip_special_tokens=True)

    print("  Pre-parsing sentences...")
    docs = {text: source_nlp(text) for text in tqdm(texts, desc="  Parsing original sentences")}
    translated_docs = {translated_text: target_nlp(translated_text) for translated_text in tqdm(translations.values(), desc="  Parsing translated sentences")}

    print("  Generating swaps...")
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="  Generating swaps"):
        sentence = row["text"]
        row_data = {
            "original_text": sentence,
            "label": row["label"],
            "no_eligible_count": 0,
            "no_candidates_count": 0
        }

        doc = docs[sentence]
        translated_sentence = translations.get(sentence)
        translated_doc = translated_docs.get(translated_sentence) if translated_sentence else None

        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                swap_result = swap_word_fast(
                    sentence, doc, translated_doc,
                    source_lang=source_lang, pos=pos, position=position
                )
                key = f"{pos}_{position}"
                if swap_result == "no_eligible":
                    row_data["no_eligible_count"] += 1
                    row_data[f"{key}_sentence"] = None
                elif swap_result == "no_candidates":
                    row_data["no_candidates_count"] += 1
                    row_data[f"{key}_sentence"] = None
                else:
                    row_data[f"{key}_sentence"] = swap_result["sentence"]
                    row_data[f"{key}_original_word"] = swap_result["original_word"]
                    row_data[f"{key}_replacement"] = swap_result["replacement"]
                    row_data[f"{key}_similarity"] = swap_result["similarity"]

        all_rows_data.append(row_data)
    return all_rows_data

def analyze_pregenerated_swaps_with_sentiment(pregenerated_rows_data, model_pipeline, model_key):
    """
    Takes pre-generated swap data and evaluates sentiment using the given model.
    """
    print(f"Collecting sentences for {model_key} sentiment analysis...")
    all_sentences_for_sentiment = []
    for row_data in pregenerated_rows_data:
        all_sentences_for_sentiment.append(row_data["original_text"])
        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                key = f"{pos}_{position}"
                if row_data.get(f"{key}_sentence") is not None:
                    all_sentences_for_sentiment.append(row_data[f"{key}_sentence"])

    unique_sentences = list(dict.fromkeys(all_sentences_for_sentiment))
    print(f"Running {model_key} sentiment on {len(unique_sentences)} unique sentences...")

    sentiment_results = model_pipeline(
        unique_sentences,
        batch_size=64,
        truncation=True,
        max_length=512
    )

    sentiment_map = {}
    for sentence, result in zip(unique_sentences, sentiment_results):
        label = result["label"]
        score = result["score"]
        if model_key == "mbert":
            numeric = int(label.split()[0])
        elif model_key == "xlm_roberta":
            label_map = {"negative": 1, "neutral": 3, "positive": 5}
            numeric = label_map.get(label.lower(), 3)
        elif model_key == "distilbert":
            label_map = {"negative": 1, "positive": 5}
            numeric = label_map.get(label.lower(), 3)
        sentiment_map[sentence] = (numeric, score)

    print("Assembling final results with sentiment scores...")
    final_results = []
    for row_data in pregenerated_rows_data:
        current_row_data = row_data.copy() # Make a copy to add sentiment scores
        orig_score, orig_conf = sentiment_map[current_row_data["original_text"]]
        current_row_data["original_score"] = orig_score
        current_row_data["original_confidence"] = orig_conf

        for pos in ["NOUN", "ADJ", "VERB"]:
            for position in ["beginning", "middle", "end"]:
                key = f"{pos}_{position}"
                swapped_sentence = current_row_data.get(f"{key}_sentence")
                if swapped_sentence is not None:
                    swap_score, swap_conf = sentiment_map[swapped_sentence]
                    current_row_data[f"{key}_score"] = swap_score
                    current_row_data[f"{key}_confidence"] = swap_conf
                    current_row_data[f"{key}_score_diff"] = swap_score - orig_score

        all_results.append(current_row_data)

    return pd.DataFrame(final_results)


# --- Main execution flow ---
# First, generate swaps once for each language
print("\n=== Generating Swaps for English ===")
en_swaps_data = _preprocess_and_generate_swaps(df_en_sample, source_lang="en")

print("\n=== Generating Swaps for Spanish ===")
es_swaps_data = _preprocess_and_generate_swaps(df_es_sample, source_lang="es")


# Then, iterate through models and evaluate sentiment using the pre-generated swaps
all_model_results = {}
for model_key, model_name in models_to_test.items():
    print(f"\n{'='*60}")
    print(f"Loading {model_key}: {model_name}")
    print(f"{'='*60}")

    try:
        model_pipeline = pipeline(
            "sentiment-analysis",
            model=model_name,
            device=0 if torch.cuda.is_available() else -1
        )

        print(f"\nAnalyzing English dataset with {model_key}...")
        df_en = analyze_pregenerated_swaps_with_sentiment(
            en_swaps_data, model_pipeline=model_pipeline, model_key=model_key
        )

        print(f"\nAnalyzing Spanish dataset with {model_key}...")
        df_es = analyze_pregenerated_swaps_with_sentiment(
            es_swaps_data, model_pipeline=model_pipeline, model_key=model_key
        )

        all_model_results[model_key] = {"en": df_en, "es": df_es}

        # Save each model's results
        df_en.to_parquet(f"/content/drive/MyDrive/{model_key}_en_results.parquet", index=False)
        df_es.to_parquet(f"/content/drive/MyDrive/{model_key}_es_results.parquet", index=False)

        print(f"Saved {model_key} results to Drive")

        # Free GPU memory before loading next model
        del model_pipeline
        torch.cuda.empty_cache()
        import gc
        gc.collect()

    except Exception as e:
        print(f"Failed on {model_key}: {e}")
        continue

print("\nAll models done!")

"""Cross Analysis"""

# @title
import pickle

# ================================================================
# SAVE SWAP DATA (run once)
# ================================================================
# print("Saving pre-generated swap data...")
# with open("/content/drive/MyDrive/en_swaps_data.pkl", "wb") as f:
#     pickle.dump(en_swaps_data, f)
# with open("/content/drive/MyDrive/es_swaps_data.pkl", "wb") as f:
#     pickle.dump(es_swaps_data, f)
# print("Swap data saved!")

# ================================================================
# RELOAD SWAP DATA (use in future sessions instead of regenerating)
# ================================================================
with open("/content/drive/MyDrive/en_swaps_data.pkl", "rb") as f:
    en_swaps_data = pickle.load(f)
with open("/content/drive/MyDrive/es_swaps_data.pkl", "rb") as f:
    es_swaps_data = pickle.load(f)

# @title
def compare_all_models(all_model_results, lang="en"):
    print(f"\n{'='*60}")
    print(f"Model Comparison - {lang.upper()} - Flip Rate")
    print(f"{'='*60}\n")

    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    keys = [f"{pos}_{pos_}" for pos in pos_tags for pos_ in positions]

    print(f"{'':20}", end="")
    for key in keys:
        print(f"{key:>18}", end="")
    print()
    print("-" * (20 + 18 * len(keys)))

    for model_key, results in all_model_results.items():
        df = results[lang]
        print(f"{model_key:<20}", end="")
        for key in keys:
            diff_col = f"{key}_score_diff"
            sentence_col = f"{key}_sentence"
            if sentence_col not in df.columns:
                print(f"{'N/A':>18}", end="")
                continue
            swapped = df[sentence_col].notna()
            total = swapped.sum()
            if total == 0:
                print(f"{'0/0':>18}", end="")
                continue
            flipped = (df.loc[swapped, diff_col] != 0).sum()
            rate = flipped / total * 100
            print(f"{rate:>17.1f}%", end="")
        print()

compare_all_models(all_model_results, lang="en")
compare_all_models(all_model_results, lang="es")

# @title
from sentence_transformers import SentenceTransformer, util
import numpy as np
import pandas as pd
from tqdm import tqdm

# Load LaBSE for semantic similarity (better for multilingual)
labse_model = SentenceTransformer("sentence-transformers/LaBSE", device=device)

# ================================================================
# METRIC 1: Flip Rate (FR)
# ================================================================
def compute_flip_rate(df_results, lang=""):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    flip_rates = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"Flip Rate {lang}"):
        key = f"{pos}_{position}"
        diff_col = f"{key}_score_diff"
        sentence_col = f"{key}_sentence"

        if sentence_col not in df_results.columns:
            continue

        swapped = df_results[sentence_col].notna()
        total = swapped.sum()
        if total == 0:
            continue

        flipped = (df_results.loc[swapped, diff_col] != 0).sum()
        flip_rates[key] = {
            "flipped": int(flipped),
            "total": int(total),
            "rate": float(flipped / total)
        }

    return flip_rates


# ================================================================
# METRIC 2: Minimum Swap Distance to Flip (MSDF)
# ================================================================
# def compute_msdf(df, source_lang="en", max_swaps=9):
#     ...


# ================================================================
# METRIC 3: Semantic Similarity (SemSim)
# ================================================================
def compute_semsim(df_results, lang=""):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    semsim_results = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"SemSim {lang}"):
        key = f"{pos}_{position}"
        sentence_col = f"{key}_sentence"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()]
        if len(valid) == 0:
            continue

        orig_sentences = valid["original_text"].tolist()
        swap_sentences = valid[sentence_col].tolist()

        orig_embeddings = labse_model.encode(orig_sentences,
                                              batch_size=64,
                                              convert_to_numpy=True,
                                              show_progress_bar=False)
        swap_embeddings = labse_model.encode(swap_sentences,
                                              batch_size=64,
                                              convert_to_numpy=True,
                                              show_progress_bar=False)

        sims = [float(util.cos_sim(o, s))
                for o, s in zip(orig_embeddings, swap_embeddings)]

        diff_col = f"{key}_score_diff"
        high_sim_mask = np.array(sims) >= 0.8
        flipped = (valid[diff_col].values != 0)

        flip_at_high_sim = (high_sim_mask & flipped).sum()
        total_high_sim = high_sim_mask.sum()

        semsim_results[key] = {
            "mean_similarity": float(np.mean(sims)),
            "flip_rate_at_high_sim": float(flip_at_high_sim / total_high_sim)
                                      if total_high_sim > 0 else 0.0,
            "total_high_sim": int(total_high_sim)
        }

    return semsim_results


# ================================================================
# METRIC 4: Robustness Gap
# ================================================================
def compute_robustness_gap(df_results, lang=""):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    label_map = {0: 1, 1: 3, 2: 5}

    def is_correct(pred_score, true_label):
        true_score = label_map.get(true_label)
        if true_score is None:
            return False
        def to_class(s):
            if s <= 2: return "negative"
            elif s == 3: return "neutral"
            else: return "positive"
        return to_class(pred_score) == to_class(true_score)

    orig_correct = df_results.apply(
        lambda r: is_correct(r["original_score"], r["label"]), axis=1
    ).mean()

    gaps = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"Robustness Gap {lang}"):
        key = f"{pos}_{position}"
        score_col = f"{key}_score"
        sentence_col = f"{key}_sentence"

        if score_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()].copy()
        if len(valid) == 0:
            continue

        swap_correct = valid.apply(
            lambda r: is_correct(r[score_col], r["label"]), axis=1
        ).mean()

        gaps[key] = {
            "original_accuracy": float(orig_correct),
            "swapped_accuracy": float(swap_correct),
            "robustness_gap": float(orig_correct - swap_correct)
        }

    return gaps


# ================================================================
# METRIC 5: Flip Rate by Language Mixing Index (LMI)
# ================================================================
def compute_lmi(sentence, lang="en"):
    words = sentence.lower().split()
    if not words:
        return 0.0

    other_lang = "es" if lang == "en" else "en"
    other_count = sum(
        1 for w in words
        if word_frequency(w, other_lang) > word_frequency(w, lang)
    )
    return other_count / len(words)

def compute_flip_rate_by_lmi(df_results, source_lang="en", n_bins=5):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    lmi_flip_data = []
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc=f"LMI {source_lang.upper()}"):
        key = f"{pos}_{position}"
        sentence_col = f"{key}_sentence"
        diff_col = f"{key}_score_diff"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()].copy()
        if len(valid) == 0:
            continue

        valid["lmi"] = valid[sentence_col].apply(
            lambda s: compute_lmi(s, lang=source_lang)
        )
        valid["flipped"] = valid[diff_col] != 0
        valid["swap_key"] = key
        lmi_flip_data.append(valid[["lmi", "flipped", "swap_key"]])

    if not lmi_flip_data:
        return None

    combined = pd.concat(lmi_flip_data)
    combined["lmi_bin"] = pd.cut(combined["lmi"], bins=n_bins)
    lmi_summary = combined.groupby("lmi_bin")["flipped"].agg(["mean", "count"])
    lmi_summary.columns = ["flip_rate", "count"]
    return lmi_summary


# ================================================================
# METRIC 6: Per-Language-Pair Asymmetry
# ================================================================
def compute_asymmetry(df_en_results, df_es_results):
    pos_tags = ["NOUN", "ADJ", "VERB"]
    positions = ["beginning", "middle", "end"]
    asymmetry = {}
    combos = [(pos, position) for pos in pos_tags for position in positions]

    for pos, position in tqdm(combos, desc="Asymmetry EN↔ES"):
        key = f"{pos}_{position}"
        diff_col = f"{key}_score_diff"
        sentence_col = f"{key}_sentence"

        if sentence_col in df_en_results.columns:
            en_valid = df_en_results[df_en_results[sentence_col].notna()]
            en_flips = (en_valid[diff_col] != 0).sum()
            en_total = len(en_valid)
            en_rate = en_flips / en_total if en_total > 0 else 0
        else:
            en_rate, en_total = 0, 0

        if sentence_col in df_es_results.columns:
            es_valid = df_es_results[df_es_results[sentence_col].notna()]
            es_flips = (es_valid[diff_col] != 0).sum()
            es_total = len(es_valid)
            es_rate = es_flips / es_total if es_total > 0 else 0
        else:
            es_rate, es_total = 0, 0

        asymmetry[key] = {
            "en_to_es_flip_rate": float(en_rate),
            "es_to_en_flip_rate": float(es_rate),
            "asymmetry": float(en_rate - es_rate)
        }

    return asymmetry

# @title
def print_all_metrics(fr, semsim, gap, lmi, asymmetry, msdf=None, lang="en"):
    print(f"\n{'='*60}")
    print(f"FULL METRICS REPORT - {lang.upper()}")
    print(f"{'='*60}")

    print(f"\n--- Flip Rate ---")
    for key, val in fr.items():
        print(f"{key:<20} {val['flipped']}/{val['total']} "
              f"({val['rate']*100:.1f}%)")

    print(f"\n--- Semantic Similarity & Flip Rate at High SemSim ---")
    for key, val in semsim.items():
        print(f"{key:<20} mean_sim={val['mean_similarity']:.3f} "
              f"flip@sim>=0.8={val['flip_rate_at_high_sim']*100:.1f}% "
              f"(n={val['total_high_sim']})")

    print(f"\n--- Robustness Gap ---")
    for key, val in gap.items():
        print(f"{key:<20} orig_acc={val['original_accuracy']*100:.1f}% "
              f"swap_acc={val['swapped_accuracy']*100:.1f}% "
              f"gap={val['robustness_gap']*100:.1f}%")

    print(f"\n--- LMI Flip Rate ---")
    print(lmi)

    print(f"\n--- Asymmetry (en->es vs es->en) ---")
    for key, val in asymmetry.items():
        print(f"{key:<20} en->es={val['en_to_es_flip_rate']*100:.1f}% "
              f"es->en={val['es_to_en_flip_rate']*100:.1f}% "
              f"diff={val['asymmetry']*100:+.1f}%")

    if msdf is not None:
        print(f"\n--- MSDF ---")
        print(f"Mean min swaps to flip: {msdf['min_swaps_to_flip'].mean():.2f}")
        print(f"Never flipped: {msdf['min_swaps_to_flip'].isna().sum()} sentences")
        print(msdf['min_swaps_to_flip'].value_counts().sort_index())

# @title
# ================================================================
# RELOAD ALL MODEL RESULTS
# ================================================================
models_to_test = {
    "mbert": "nlptown/bert-base-multilingual-uncased-sentiment",
    "xlm_roberta": "cardiffnlp/twitter-xlm-roberta-base-sentiment",
    "distilbert": "lxyuan/distilbert-base-multilingual-cased-sentiments-student"
}

all_model_results = {}
for model_key in models_to_test.keys():
    try:
        df_en = pd.read_parquet(f"/content/drive/MyDrive/{model_key}_en_results.parquet")
        df_es = pd.read_parquet(f"/content/drive/MyDrive/{model_key}_es_results.parquet")
        all_model_results[model_key] = {"en": df_en, "es": df_es}
        print(f"Loaded {model_key}: EN={len(df_en)} rows, ES={len(df_es)} rows")
    except Exception as e:
        print(f"Could not load {model_key}: {e}")


# ================================================================
# RUN ALL METRICS PER MODEL PER LANGUAGE
# ================================================================
all_model_metrics = {}

for model_key, results in all_model_results.items():
    print(f"\n{'='*60}")
    print(f"Computing metrics for {model_key.upper()}")
    print(f"{'='*60}")

    df_en = results["en"]
    df_es = results["es"]

    print("\nComputing Flip Rates...")
    fr_en = compute_flip_rate(df_en, lang=f"{model_key} EN")
    fr_es = compute_flip_rate(df_es, lang=f"{model_key} ES")

    print("\nComputing Semantic Similarity...")
    semsim_en = compute_semsim(df_en, lang=f"{model_key} EN")
    semsim_es = compute_semsim(df_es, lang=f"{model_key} ES")

    print("\nComputing Robustness Gap...")
    gap_en = compute_robustness_gap(df_en, lang=f"{model_key} EN")
    gap_es = compute_robustness_gap(df_es, lang=f"{model_key} ES")

    print("\nComputing LMI Flip Rates...")
    lmi_en = compute_flip_rate_by_lmi(df_en, source_lang="en")
    lmi_es = compute_flip_rate_by_lmi(df_es, source_lang="es")

    print("\nComputing Asymmetry...")
    asymmetry = compute_asymmetry(df_en, df_es)

    all_model_metrics[model_key] = {
        "fr_en": fr_en, "fr_es": fr_es,
        "semsim_en": semsim_en, "semsim_es": semsim_es,
        "gap_en": gap_en, "gap_es": gap_es,
        "lmi_en": lmi_en, "lmi_es": lmi_es,
        "asymmetry": asymmetry
    }

    # Print results for this model
    print_all_metrics(
        fr_en, semsim_en, gap_en, lmi_en, asymmetry,
        msdf=None, lang=f"{model_key} EN"
    )
    print_all_metrics(
        fr_es, semsim_es, gap_es, lmi_es, asymmetry,
        msdf=None, lang=f"{model_key} ES"
    )

print("\nAll metrics computed!")

# ================================================================
# IMPORTS AND SETUP
# ================================================================
from tqdm.notebook import tqdm
from itertools import combinations
import pickle
import random
import gc

# ================================================================
# SAMPLE 500 SENTENCES
# ================================================================
# Stratified sampling for 400 sentences, balanced by sentiment label
# Each label (0, 1, 2) will get approximately 400/3 sentences
N_SAMPLES = 400
SAMPLES_PER_LABEL = N_SAMPLES // 3 # This will be 133

df_en_500 = pd.concat([
    df_en_sample[df_en_sample['label'] == 0].sample(n=SAMPLES_PER_LABEL, random_state=42),
    df_en_sample[df_en_sample['label'] == 1].sample(n=SAMPLES_PER_LABEL, random_state=42),
    df_en_sample[df_en_sample['label'] == 2].sample(n=N_SAMPLES - (2 * SAMPLES_PER_LABEL), random_state=42) # Remaining for third label (134)
]).sample(frac=1, random_state=42).reset_index(drop=True)

df_es_500 = pd.concat([
    df_es_sample[df_es_sample['label'] == 0].sample(n=SAMPLES_PER_LABEL, random_state=42),
    df_es_sample[df_es_sample['label'] == 1].sample(n=SAMPLES_PER_LABEL, random_state=42),
    df_es_sample[df_es_sample['label'] == 2].sample(n=N_SAMPLES - (2 * SAMPLES_PER_LABEL), random_state=42) # Remaining for third label (134)
]).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"English 400 sample: {len(df_en_500)} rows")
print(df_en_500['label'].value_counts())
print(f"Spanish 400 sample: {len(df_es_500)} rows")
print(df_es_500['label'].value_counts())


# ================================================================
# MULTI-SWAP GENERATION
# ================================================================
def generate_swaps_for_sentence(sentence, doc, translated_doc,
                                 source_lang="en", max_swaps=3):
    """
    Generate swaps at each level 1..max_swaps for a single sentence.
    Each level builds on the previous swap cumulatively.
    Tracks which POS and position each swap was made at.
    Returns dict keyed by n_swaps.
    """
    nlp = nlp_en if source_lang == "en" else nlp_es
    results = {}
    excluded_words = set()
    current_sentence = sentence
    current_doc = doc
    all_swap_details = []

    for n in range(1, max_swaps + 1):
        # Try all POS/position combos in random order
        combos = [(pos, position)
                  for pos in ["NOUN", "ADJ", "VERB"]
                  for position in ["beginning", "middle", "end"]]
        random.shuffle(combos)

        swap_made = False
        for pos, position in combos:
            try:
                result = swap_word_fast(
                    current_sentence, current_doc, translated_doc,
                    source_lang=source_lang, pos=pos, position=position,
                    exclude_words=excluded_words
                )
            except Exception as e:
                print(f"Error in swap_word_fast for sentence '{current_sentence}': {e}")
                result = "no_eligible" # Treat as no eligible to skip this swap

            if isinstance(result, dict):
                excluded_words.add(result["original_word"].lower())
                current_sentence = result["sentence"]
                current_doc = nlp(current_sentence)
                all_swap_details.append({
                    "swap_n": n,
                    "pos": pos,
                    "position": position,
                    "original_word": result["original_word"],
                    "replacement": result["replacement"],
                    "similarity": result["similarity"]
                })
                swap_made = True
                break

        if swap_made:
            results[n] = {
                "sentence": current_sentence,
                "swaps": list(all_swap_details),
                "n_swaps_made": n
            }
        else:
            # Can't make more swaps
            break

    return results


def preprocess_and_generate_multi_swaps(df, source_lang="en", max_swaps=3):
    """
    Pre-translate, pre-parse, then generate swaps at each level
    for every sentence in df.
    """
    if source_lang == "en":
        tokenizer, trans_model = en_es_tokenizer, en_es_model
        source_nlp = nlp_en
        target_nlp = nlp_es
    else:
        tokenizer, trans_model = es_en_tokenizer, es_en_model
        source_nlp = nlp_es
        target_nlp = nlp_en

    texts = df["text"].tolist()
    translations = {}

    print("  Pre-translating...")
    for i in tqdm(range(0, len(texts), 64), desc="Translating"):
        batch = texts[i:i+64]
        inputs = tokenizer(batch, return_tensors="pt", padding=True,
                          truncation=True, max_length=512).to(device)
        with torch.no_grad():
            translated = trans_model.generate(**inputs)
        for src, tgt in zip(batch, translated):
            translations[src] = tokenizer.decode(tgt, skip_special_tokens=True)

    print("  Pre-parsing original sentences...")
    docs = {text: source_nlp(text)
            for text in tqdm(texts, desc="Parsing originals")}

    print("  Pre-parsing translated sentences...")
    translated_docs = {t: target_nlp(t)
                       for t in tqdm(set(translations.values()),
                                     desc="Parsing translations")}

    print("  Generating multi-swaps...")
    all_rows = []
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Generating swaps"):
        sentence = row["text"]
        doc = docs[sentence]
        translated_sentence = translations.get(sentence)
        translated_doc = translated_docs.get(translated_sentence)

        swap_results = generate_swaps_for_sentence(
            sentence, doc, translated_doc,
            source_lang=source_lang, max_swaps=max_swaps
        )

        row_data = {
            "original_text": sentence,
            "label": row["label"]
        }

        for n in range(1, max_swaps + 1):
            key = f"swap_{n}"
            if n in swap_results:
                row_data[f"{key}_sentence"] = swap_results[n]["sentence"]
                row_data[f"{key}_swaps"] = str(swap_results[n]["swaps"])
                row_data[f"{key}_n_made"] = swap_results[n]["n_swaps_made"]
            else:
                row_data[f"{key}_sentence"] = None
                row_data[f"{key}_swaps"] = None
                row_data[f"{key}_n_made"] = 0

        all_rows.append(row_data)

    return all_rows


# ================================================================
# SENTIMENT SCORING
# ================================================================
def score_multi_swap_sentiment(rows_data, model_pipeline, model_key, max_swaps=3):
    """Batch score all sentences across all swap levels."""
    all_sentences = []
    for row_data in rows_data:
        all_sentences.append(row_data["original_text"])
        for n in range(1, max_swaps + 1):
            sent = row_data.get(f"swap_{n}_sentence")
            if sent is not None:
                all_sentences.append(sent)

    unique_sentences = list(dict.fromkeys(all_sentences))
    print(f"  Running {model_key} on {len(unique_sentences)} unique sentences...")

    sentiment_results = model_pipeline(
        unique_sentences,
        batch_size=64,
        truncation=True,
        max_length=512
    )

    sentiment_map = {}
    for sentence, result in zip(unique_sentences, sentiment_results):
        label = result["label"]
        if model_key == "mbert":
            numeric = int(label.split()[0])
        elif model_key == "xlm_roberta":
            label_map = {"negative": 1, "neutral": 3, "positive": 5}
            numeric = label_map.get(label.lower(), 3)
        elif model_key == "distilbert":
            label_map = {"negative": 1, "neutral": 3, "positive": 5}
            numeric = label_map.get(label.lower(), 3)
        sentiment_map[sentence] = (numeric, result["score"])

    final_results = []
    for row_data in rows_data:
        current = row_data.copy()
        orig_score, orig_conf = sentiment_map[row_data["original_text"]]
        current["original_score"] = orig_score
        current["original_confidence"] = orig_conf

        for n in range(1, max_swaps + 1):
            key = f"swap_{n}"
            swapped = current.get(f"{key}_sentence")
            if swapped is not None:
                swap_score, swap_conf = sentiment_map[swapped]
                current[f"{key}_score"] = swap_score
                current[f"{key}_confidence"] = swap_conf
                current[f"{key}_score_diff"] = swap_score - orig_score
                current[f"{key}_flipped"] = swap_score != orig_score

        final_results.append(current)

    return pd.DataFrame(final_results)


# ================================================================
# METRICS
# ================================================================

# --- Metric 1: Flip Rate by swap count ---
def compute_flip_rate_by_n(df_results, max_swaps=3):
    rates = {}
    for n in range(1, max_swaps + 1):
        key = f"swap_{n}"
        sentence_col = f"{key}_sentence"
        flipped_col = f"{key}_flipped"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()]
        total = len(valid)
        if total == 0:
            continue

        flipped = valid[flipped_col].sum()
        rates[n] = {
            "flipped": int(flipped),
            "total": int(total),
            "rate": float(flipped / total)
        }
    return rates


# --- Metric 2: MSDF ---
def compute_msdf_from_multi(df_results, max_swaps=3):
    """
    Minimum swap distance to flip — for each sentence,
    find the minimum n at which the label first flipped.
    """
    msdf_values = []

    for idx, row in df_results.iterrows():
        min_flips = None
        for n in range(1, max_swaps + 1):
            key = f"swap_{n}"
            flipped_col = f"{key}_flipped"
            if flipped_col in df_results.columns and row.get(flipped_col) == True:
                min_flips = n
                break
        msdf_values.append(min_flips)

    df_results = df_results.copy()
    df_results["msdf"] = msdf_values
    return df_results


# --- Metric 3: SemSim ---
def compute_semsim_by_n(df_results, max_swaps=3):
    semsim_results = {}
    for n in tqdm(range(1, max_swaps + 1), desc="SemSim by swap count"):
        key = f"swap_{n}"
        sentence_col = f"{key}_sentence"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()]
        if len(valid) == 0:
            continue

        orig_embeddings = labse_model.encode(
            valid["original_text"].tolist(),
            batch_size=64, convert_to_numpy=True, show_progress_bar=False
        )
        swap_embeddings = labse_model.encode(
            valid[sentence_col].tolist(),
            batch_size=64, convert_to_numpy=True, show_progress_bar=False
        )

        sims = [float(util.cos_sim(o, s))
                for o, s in zip(orig_embeddings, swap_embeddings)]

        flipped = valid[f"{key}_flipped"].values
        high_sim_mask = np.array(sims) >= 0.8
        flip_at_high_sim = (high_sim_mask & flipped).sum()
        total_high_sim = high_sim_mask.sum()

        semsim_results[n] = {
            "mean_similarity": float(np.mean(sims)),
            "flip_rate_at_high_sim": float(flip_at_high_sim / total_high_sim)
                                      if total_high_sim > 0 else 0.0,
            "total_high_sim": int(total_high_sim)
        }

    return semsim_results


# --- Metric 4: Robustness Gap ---
def compute_robustness_gap_by_n(df_results, max_swaps=3):
    label_map = {0: 1, 1: 3, 2: 5}

    def is_correct(pred_score, true_label):
        true_score = label_map.get(true_label)
        if true_score is None:
            return False
        def to_class(s):
            if s <= 2: return "negative"
            elif s == 3: return "neutral"
            else: return "positive"
        return to_class(pred_score) == to_class(true_score)

    orig_correct = df_results.apply(
        lambda r: is_correct(r["original_score"], r["label"]), axis=1
    ).mean()

    gaps = {}
    for n in tqdm(range(1, max_swaps + 1), desc="Robustness Gap by swap count"):
        key = f"swap_{n}"
        score_col = f"{key}_score"
        sentence_col = f"{key}_sentence"

        if score_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()].copy()
        if len(valid) == 0:
            continue

        swap_correct = valid.apply(
            lambda r: is_correct(r[score_col], r["label"]), axis=1
        ).mean()

        gaps[n] = {
            "original_accuracy": float(orig_correct),
            "swapped_accuracy": float(swap_correct),
            "robustness_gap": float(orig_correct - swap_correct)
        }

    return gaps


# --- Metric 5: LMI ---
def compute_lmi_by_n(df_results, source_lang="en", max_swaps=3, n_bins=5):
    lmi_results = {}
    for n in tqdm(range(1, max_swaps + 1), desc="LMI by swap count"):
        key = f"swap_{n}"
        sentence_col = f"{key}_sentence"
        flipped_col = f"{key}_flipped"

        if sentence_col not in df_results.columns:
            continue

        valid = df_results[df_results[sentence_col].notna()].copy()
        if len(valid) == 0:
            continue

        valid["lmi"] = valid[sentence_col].apply(
            lambda s: compute_lmi(s, lang=source_lang)
        )
        valid["lmi_bin"] = pd.cut(valid["lmi"], bins=n_bins)
        summary = valid.groupby("lmi_bin")[flipped_col].agg(["mean", "count"])
        summary.columns = ["flip_rate", "count"]
        lmi_results[n] = summary

    return lmi_results


# --- Metric 6: Asymmetry ---
def compute_asymmetry_by_n(df_en_results, df_es_results, max_swaps=3):
    asymmetry = {}
    for n in range(1, max_swaps + 1):
        key = f"swap_{n}"
        flipped_col = f"{key}_flipped"
        sentence_col = f"{key}_sentence"

        en_valid = df_en_results[df_en_results[sentence_col].notna()] \
            if sentence_col in df_en_results.columns else pd.DataFrame()
        es_valid = df_es_results[df_es_results[sentence_col].notna()] \
            if sentence_col in df_es_results.columns else pd.DataFrame()

        en_rate = en_valid[flipped_col].mean() if len(en_valid) > 0 else 0
        es_rate = es_valid[flipped_col].mean() if len(es_valid) > 0 else 0

        asymmetry[n] = {
            "en_to_es_flip_rate": float(en_rate),
            "es_to_en_flip_rate": float(es_rate),
            "asymmetry": float(en_rate - es_rate)
        }

    return asymmetry


# --- Print all metrics ---
def print_all_metrics_by_n(fr, semsim, gap, lmi, asymmetry, msdf_df,
                            lang="en", max_swaps=3):
    print(f"\n{'='*60}")
    print(f"METRICS REPORT — {lang.upper()}")
    print(f"{'='*60}")

    print(f"\n--- Flip Rate by Swap Count ---")
    print(f"{'N swaps':<12} {'Flipped':<10} {'Total':<10} {'Rate'}")
    print("-" * 42)
    for n, val in fr.items():
        print(f"{n:<12} {val['flipped']:<10} {val['total']:<10} "
              f"{val['rate']*100:.1f}%")

    print(f"\n--- MSDF (Minimum Swaps to Flip) ---")
    msdf_counts = msdf_df["msdf"].value_counts().sort_index()
    never_flipped = msdf_df["msdf"].isna().sum()
    mean_msdf = msdf_df["msdf"].mean()
    print(f"Mean MSDF: {mean_msdf:.2f}")
    print(f"Never flipped: {never_flipped} / {len(msdf_df)} sentences")
    for n, count in msdf_counts.items():
        print(f"  Flipped at swap {int(n)}: {count} sentences")

    print(f"\n--- Semantic Similarity by Swap Count ---")
    for n, val in semsim.items():
        print(f"Swap {n}: mean_sim={val['mean_similarity']:.3f} "
              f"flip@sim>=0.8={val['flip_rate_at_high_sim']*100:.1f}% "
              f"(n={val['total_high_sim']})")

    print(f"\n--- Robustness Gap by Swap Count ---")
    for n, val in gap.items():
        print(f"Swap {n}: orig_acc={val['original_accuracy']*100:.1f}% "
              f"swap_acc={val['swapped_accuracy']*100:.1f}% "
              f"gap={val['robustness_gap']*100:.1f}%")

    print(f"\n--- LMI Flip Rate by Swap Count ---")
    for n, summary in lmi.items():
        print(f"\nSwap {n}:")
        print(summary.to_string())

    print(f"\n--- Asymmetry by Swap Count ---")
    for n, val in asymmetry.items():
        print(f"Swap {n}: en->es={val['en_to_es_flip_rate']*100:.1f}% "
              f"es->en={val['es_to_en_flip_rate']*100:.1f}% "
              f"diff={val['asymmetry']*100:+.1f}%")


# ================================================================
# MAIN EXECUTION
# ================================================================
MAX_SWAPS = 3

print("=== Generating Multi-Swap Data ===")
en_multi_swaps = preprocess_and_generate_multi_swaps(
    df_en_500, source_lang="en", max_swaps=MAX_SWAPS
)
es_multi_swaps = preprocess_and_generate_multi_swaps(
    df_es_500, source_lang="es", max_swaps=MAX_SWAPS
)

# Save swap data
with open("/content/drive/MyDrive/en_multi_swaps_500.pkl", "wb") as f:
    pickle.dump(en_multi_swaps, f)
with open("/content/drive/MyDrive/es_multi_swaps_500.pkl", "wb") as f:
    pickle.dump(es_multi_swaps, f)
print("Swap data saved!")

# Score and compute metrics for each model
all_multi_results = {}

for model_key, model_name in models_to_test.items():
    print(f"\n{'='*60}")
    print(f"Model: {model_key}")
    print(f"{'='*60}")

    try:
        model_pipeline = pipeline(
            "sentiment-analysis",
            model=model_name,
            device=0 if torch.cuda.is_available() else -1
        )

        print("\nScoring English...")
        df_en_multi = score_multi_swap_sentiment(
            en_multi_swaps, model_pipeline, model_key, max_swaps=MAX_SWAPS
        )

        print("\nScoring Spanish...")
        df_es_multi = score_multi_swap_sentiment(
            es_multi_swaps, model_pipeline, model_key, max_swaps=MAX_SWAPS
        )

        # Compute MSDF
        df_en_multi = compute_msdf_from_multi(df_en_multi, max_swaps=MAX_SWAPS)
        df_es_multi = compute_msdf_from_multi(df_es_multi, max_swaps=MAX_SWAPS)

        # Save results
        df_en_multi.to_parquet(
            f"/content/drive/MyDrive/{model_key}_en_multi_500.parquet", index=False
        )
        df_es_multi.to_parquet(
            f"/content/drive/MyDrive/{model_key}_es_multi_500.parquet", index=False
        )

        # Compute all metrics
        print("\nComputing metrics...")
        fr_en = compute_flip_rate_by_n(df_en_multi, max_swaps=MAX_SWAPS)
        fr_es = compute_flip_rate_by_n(df_es_multi, max_swaps=MAX_SWAPS)

        semsim_en = compute_semsim_by_n(df_en_multi, max_swaps=MAX_SWAPS)
        semsim_es = compute_semsim_by_n(df_es_multi, max_swaps=MAX_SWAPS)

        gap_en = compute_robustness_gap_by_n(df_en_multi, max_swaps=MAX_SWAPS)
        gap_es = compute_robustness_gap_by_n(df_es_multi, max_swaps=MAX_SWAPS)

        lmi_en = compute_lmi_by_n(df_en_multi, source_lang="en", max_swaps=MAX_SWAPS)
        lmi_es = compute_lmi_by_n(df_es_multi, source_lang="es", max_swaps=MAX_SWAPS)

        asymmetry = compute_asymmetry_by_n(df_en_multi, df_es_multi, max_swaps=MAX_SWAPS)

        all_multi_results[model_key] = {
            "en": df_en_multi, "es": df_es_multi,
            "fr_en": fr_en, "fr_es": fr_es,
            "semsim_en": semsim_en, "semsim_es": semsim_es,
            "gap_en": gap_en, "gap_es": gap_es,
            "lmi_en": lmi_en, "lmi_es": lmi_es,
            "asymmetry": asymmetry
        }

        # Print metrics
        print_all_metrics_by_n(
            fr_en, semsim_en, gap_en, lmi_en, asymmetry,
            df_en_multi, lang=f"{model_key} EN", max_swaps=MAX_SWAPS
        )
        print_all_metrics_by_n(
            fr_es, semsim_es, gap_es, lmi_es, asymmetry,
            df_es_multi, lang=f"{model_key} ES", max_swaps=MAX_SWAPS
        )

        del model_pipeline
        torch.cuda.empty_cache()
        gc.collect()

    except Exception as e:
        print(f"Failed on {model_key}: {e}")
        continue

print("\nAll done!")

# Reload swap data
with open("/content/drive/MyDrive/en_multi_swaps_500.pkl", "rb") as f:
    en_multi_swaps = pickle.load(f)
with open("/content/drive/MyDrive/es_multi_swaps_500.pkl", "rb") as f:
    es_multi_swaps = pickle.load(f)

# Reload results and recompute metrics
all_multi_results = {}
for model_key in models_to_test.keys():
    try:
        df_en = pd.read_parquet(f"/content/drive/MyDrive/{model_key}_en_multi_500.parquet")
        df_es = pd.read_parquet(f"/content/drive/MyDrive/{model_key}_es_multi_500.parquet")
        all_multi_results[model_key] = {"en": df_en, "es": df_es}
        print(f"Loaded {model_key}")
    except Exception as e:
        print(f"Could not load {model_key}: {e}")